In [24]:
import torch
import torch.nn as nn

# 2个神经元的输出y的数值为
y = torch.randn(2)
print(y)
m = nn.Softmax(dim=0)
out = m(y)
print(out)

tensor([1.4891, 1.1289])
tensor([0.5891, 0.4109])


In [25]:
x = torch.randint(0, 255, (1, 128*128), dtype=torch.float32)
fc = nn.Linear(128*128, 2)
y = fc(x)
print(y)
# 注意y的shape是(1, 2)
output = nn.Softmax(dim=1)(y)
print(output)

tensor([[13.5282, 27.1557]], grad_fn=<AddmmBackward0>)
tensor([[1.2069e-06, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
