In [1]:
import torch
import torch.nn as nn
import numpy as np
input_feat = torch.tensor([[[[1, 2], [3, 4]]]], dtype=torch.float32)
input_feat

tensor([[[[1., 2.],
          [3., 4.]]]])

In [2]:
kernels = torch.tensor([[[[1, 0], [1, 1]]]], dtype=torch.float32)
kernels


tensor([[[[1., 0.],
          [1., 1.]]]])

In [3]:
convTrans = nn.ConvTranspose2d(1, 1, kernel_size=2, stride=1, padding=0, bias = False)
convTrans.weight=nn.Parameter(kernels)

In [4]:
convTrans(input_feat)

tensor([[[[1., 2., 0.],
          [4., 7., 2.],
          [3., 7., 4.]]]], grad_fn=<ConvolutionBackward0>)