In [20]:
import torch

KeyboardInterrupt: 

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.0.1'

In [4]:
arr_1_d = np.asarray([1])

In [5]:
print(arr_1_d)

[1]


In [6]:
arr_2_d = np.asarray([[1,2],[3,4]])

In [7]:
print(arr_2_d)

[[1 2]
 [3 4]]


In [8]:
arr_1_d.ndim

1

In [9]:
arr_2_d.ndim

2

In [10]:
arr_1_d.shape

(1,)

In [11]:
arr_2_d.shape

(2, 2)

In [12]:
arr_2_d.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [13]:
a = np.arange(6).reshape(2,3)

In [14]:
arr_2_d.size

4

In [15]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(shape=(2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(2,5)

array([2, 3, 4])

In [19]:
np.arange(2,9,3)

array([2, 5, 8])

In [21]:
print("hello")

hello
