In [24]:
import torch

torch.rand(10)

tensor([0.9316, 0.0439, 0.9209, 0.4770, 0.7882, 0.9050, 0.0659, 0.1299, 0.3917,
        0.5425])

In [25]:
torch.randn(10)

tensor([-0.2121, -1.1152,  0.7389,  1.0554,  1.5733,  1.4783, -0.3741, -0.5944,
         0.2422, -0.8898])

In [26]:
a = torch.tensor(1)

In [27]:
b = a.item()

In [28]:
a = [1,2,3]
b = torch.tensor(a)
c = b.numpy().tolist()


In [29]:
a=torch.zeros(2, 3, 5)
a.shape

torch.Size([2, 3, 5])

In [30]:
a.size()

torch.Size([2, 3, 5])

In [31]:
a.numel()

30

In [32]:
x = torch.rand(2,3,5)
x.shape

torch.Size([2, 3, 5])

In [33]:
x = x.permute(2,1,0)
x.shape

torch.Size([5, 3, 2])

In [34]:
x = torch.rand(2,3,4)
x.shape

torch.Size([2, 3, 4])

In [35]:
x = x.transpose(1,0)
x.shape

torch.Size([3, 2, 4])

形状变换

In [36]:
x = torch.rand(4,4)
x.shape 



torch.Size([4, 4])

In [37]:
x = x.view(2,8)
x.shape

torch.Size([2, 8])

In [38]:
x = x.permute(1,0)
x.shape
x = x.reshape(4,4)
x.view(4,4)

tensor([[0.2450, 0.6576, 0.0905, 0.4121],
        [0.5718, 0.5899, 0.8018, 0.4308],
        [0.9883, 0.8454, 0.9037, 0.8523],
        [0.9698, 0.7426, 0.3204, 0.4974]])

增减维度

In [39]:
x = torch.rand(2,1,3)
x.shape
y = x.squeeze(1)
y.shape
z = y.squeeze(1)
z.shape

torch.Size([2, 3])

In [43]:
x = torch.rand(2,1,3)
y = x.unsqueeze(2)
y.shape

torch.Size([2, 1, 1, 3])