## Tensor 的连接操作

Cat

In [2]:
import torch 


In [3]:
A = torch.ones(3,3)
B = 2 * torch.ones(3,3) 
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
B

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [5]:
C = torch.cat((A,B),0)
C

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
D = torch.cat((A,B),1)
D

tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])

Stack cat 实际上是将多个 Tensor 在已有的维度上进行连接，那如果想增加新的维度进行连接，又该怎么做呢？这时候就需要 stack 函数登场了。

In [7]:
A = torch.arange(0,4)
A

tensor([0, 1, 2, 3])

In [8]:
B = torch.arange(5,9)
B

tensor([5, 6, 7, 8])

In [9]:
C = torch.stack((A,B),0)
C

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])

In [10]:
D = torch.stack((A,B),1)
D

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])

# Tensor 的切分操作

### chunk 
chunk 的作用就是将 Tensor 按照声明的 dim，进行尽可能平均的划分。

In [15]:
A = torch.tensor([1,2,3,4,5,6,7,8,9,10])
B = torch.chunk(A,2,0)
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [16]:
B = torch.chunk(A,3,0)
B

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10]))

### splite

In [17]:
A = torch.rand(4,4)
A

tensor([[0.9799, 0.8076, 0.1011, 0.6013],
        [0.2529, 0.8626, 0.7419, 0.4375],
        [0.7387, 0.0617, 0.0953, 0.3841],
        [0.6865, 0.0141, 0.0576, 0.4682]])

In [18]:
B = torch.split(A,2,0)
B

(tensor([[0.9799, 0.8076, 0.1011, 0.6013],
         [0.2529, 0.8626, 0.7419, 0.4375]]),
 tensor([[0.7387, 0.0617, 0.0953, 0.3841],
         [0.6865, 0.0141, 0.0576, 0.4682]]))

In [19]:
C = torch.split(A,3,0)
C

(tensor([[0.9799, 0.8076, 0.1011, 0.6013],
         [0.2529, 0.8626, 0.7419, 0.4375],
         [0.7387, 0.0617, 0.0953, 0.3841]]),
 tensor([[0.6865, 0.0141, 0.0576, 0.4682]]))

In [20]:
A = torch.rand(5,4)
A

tensor([[0.8300, 0.3883, 0.1201, 0.1674],
        [0.5653, 0.9271, 0.7623, 0.8380],
        [0.8328, 0.2156, 0.3683, 0.4157],
        [0.4080, 0.8806, 0.4369, 0.0265],
        [0.3405, 0.4693, 0.4433, 0.2155]])

In [27]:
B = torch.split(A,(2,3),0)
B

(tensor([[0.8300, 0.3883, 0.1201, 0.1674],
         [0.5653, 0.9271, 0.7623, 0.8380]]),
 tensor([[0.8328, 0.2156, 0.3683, 0.4157],
         [0.4080, 0.8806, 0.4369, 0.0265],
         [0.3405, 0.4693, 0.4433, 0.2155]]))

### unbind

In [29]:
A = torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [30]:
b = torch.unbind(A,0)
b 

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]))

In [31]:
b = torch.unbind(A,1)
b

(tensor([ 0,  4,  8, 12]),
 tensor([ 1,  5,  9, 13]),
 tensor([ 2,  6, 10, 14]),
 tensor([ 3,  7, 11, 15]))

Index 

In [32]:
A = torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [33]:
B = torch.index_select(A,0,torch.tensor([1,3]))
B

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [34]:
C = torch.index_select(A,1,torch.tensor([0,3]))
C

tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])

In [36]:
A = torch.rand(5)
A

tensor([0.6155, 0.5488, 0.0283, 0.5960, 0.5046])

In [37]:
B = A> 0.3
B

tensor([ True,  True, False,  True,  True])

In [38]:
C = torch.masked_select(A,B)
C

tensor([0.6155, 0.5488, 0.5960, 0.5046])