In [6]:
import torch 


In [7]:
from torch.utils.data import Dataset

In [8]:
class MyDataset(Dataset):
		def __init__(self,data_tensor,target_tensor):
					self.data_tensor = data_tensor
					self.target_tensor = target_tensor
    
		def __len__(self):
    		 	return self.data_tensor.size(0)
    
		def __getitem__(self,index):
    			return self.data_tensor[index], self.target_tensor[index]
		

In [9]:
data_tensor = torch.randn(10,3)
target_tensor = torch.randint(2,(10,))

In [10]:
my_dataset = MyDataset(data_tensor,target_tensor)
print('dataset size :',len(my_dataset))
print('tensor_data[0]:',my_dataset[0])

dataset size : 10
tensor_data[0]: (tensor([0.3595, 0.4658, 0.0865]), tensor(1))


# DataLoader 类
在实际项目中，如果数据量很大，考虑到内存有限、I/O 速度等问题，在训练过程中不可能一次性的将所有数据全部加载到内存中，也不能只用一个进程去加载，所以就需要多进程、迭代加载，而 DataLoader 就是基于这些需要被设计出来的。DataLoader 是一个迭代器，最基本的使用方法就是传入一个 Dataset 对象，它会根据参数 batch_size 的值生成一个 batch 的数据，节省内存的同时，它还可以实现多进程、数据打乱等处理。

In [11]:
from torch.utils.data import DataLoader
tensor_dataloader = DataLoader(dataset=my_dataset,
                               batch_size=2,
                               shuffle=True,
                               num_workers=0
															 )

for data,target in tensor_dataloader:
    print(data,target)

tensor([[ 0.0483, -0.4663, -1.9162],
        [ 0.0819,  1.9163,  0.0573]]) tensor([0, 0])
tensor([[ 0.3595,  0.4658,  0.0865],
        [ 1.3480,  0.5413, -1.2645]]) tensor([1, 0])
tensor([[ 1.9180, -0.2072, -1.9213],
        [-0.5140,  1.1048, -0.6135]]) tensor([0, 0])
tensor([[ 0.4621, -0.2023,  1.5748],
        [-0.0379,  0.1822,  0.0198]]) tensor([0, 1])
tensor([[-1.1693,  0.2365, -0.4157],
        [-0.9338, -0.4272,  1.0856]]) tensor([0, 1])


# 利用 Torchvision 读取数据

torchvision.datasets这个包本身并不包含数据集的文件本身，它的工作方式是先从网络上把数据集下载到用户指定目录，然后再用它的加载器把数据集加载到内存中。最后，把这个加载后的数据集作为对象返回给用户。

In [12]:
# 以MNIST为例
import torchvision
mnist_dataset = torchvision.datasets.MNIST(root='./data',
                                       train=True,
                                       transform=None,
                                       target_transform=None,
                                       download=False)

In [13]:
print(type(mnist_dataset))

<class 'torchvision.datasets.mnist.MNIST'>


这里我们主要以 MNIST 为例，进行了说明。其它的数据集使用方法类似，调用的时候你只要需要将类名“MNIST”换成其它数据集名字即可。对于不同的数据集，数据格式都不尽相同，而torchvision.datasets则帮助我们完成了各种不同格式的数据的解析与读取，可以说十分便捷。而对于那些没有官方接口的图像数据集，我们也可以使用以torchvision.datasets.ImageFolder接口来自行定义，在图像分类的实战篇中，就是使用 ImageFolder 进行数据读取的，你可以到那个时候再看一看。

# 数据预览

In [15]:
mnist_dataset_list = list(mnist_dataset)
mnist_dataset_list

[(<PIL.Image.Image image mode=L size=28x28>, 5),
 (<PIL.Image.Image image mode=L size=28x28>, 0),
 (<PIL.Image.Image image mode=L size=28x28>, 4),
 (<PIL.Image.Image image mode=L size=28x28>, 1),
 (<PIL.Image.Image image mode=L size=28x28>, 9),
 (<PIL.Image.Image image mode=L size=28x28>, 2),
 (<PIL.Image.Image image mode=L size=28x28>, 1),
 (<PIL.Image.Image image mode=L size=28x28>, 3),
 (<PIL.Image.Image image mode=L size=28x28>, 1),
 (<PIL.Image.Image image mode=L size=28x28>, 4),
 (<PIL.Image.Image image mode=L size=28x28>, 3),
 (<PIL.Image.Image image mode=L size=28x28>, 5),
 (<PIL.Image.Image image mode=L size=28x28>, 3),
 (<PIL.Image.Image image mode=L size=28x28>, 6),
 (<PIL.Image.Image image mode=L size=28x28>, 1),
 (<PIL.Image.Image image mode=L size=28x28>, 7),
 (<PIL.Image.Image image mode=L size=28x28>, 2),
 (<PIL.Image.Image image mode=L size=28x28>, 8),
 (<PIL.Image.Image image mode=L size=28x28>, 6),
 (<PIL.Image.Image image mode=L size=28x28>, 9),
 (<PIL.Image.Image i

In [17]:
display(mnist_dataset_list[0][0])
print("Image label is:", mnist_dataset_list[0][1])

Image label is: 5
